const REDIS_ERROR_CODES = {
  SESSION_INIT_FAILED: 'SESSION_INIT_FAILED',
  UID_GENERATE_FAILED: 'UID_GENERATE_FAILED',
  REDIS_QUERY_FAILED: 'REDIS_QUERY_FAILED',
  SESSION_DESTROY_FAILED: 'SESSION_DESTROY_FAILED'
}

module.exports = { REDIS_ERROR_CODES }