const APP_ERROR_CODES = {
  APP_ACCESS_DENIED: 'APP_ACCESS_DENIED',
}

const STANDARD_ACCESS_DENIED_ERROR = {
  code: APP_ERROR_CODES.APP_ACCESS_DENIED,
  message: 'Access denied'
}

module.exports = { APP_ERROR_CODES, STANDARD_ACCESS_DENIED_ERROR }